---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
        exclude: .github/workflows/
      - id: trailing-whitespace

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.6.9
    hooks:
      - id: actionlint

minimum_pre_commit_version: !!str 2.16
