---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
        exclude: .github/workflows/
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.6.13
    hooks:
      - id: actionlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      # - id: terraform_tflint
      - id: terraform_validate

minimum_pre_commit_version: !!str 2.16
