---
name: Dependabot auto-merge

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        name: Dependabot metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr merge --auto --rebase '${{github.event.pull_request.html_url}}'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
