# yamllint disable rule:line-length
---
name: Pull Request

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: set PY
        run: |
          PY="$(python --version --version | sha256sum | cut -d' ' -f1)"
          printf 'PY=%s\n' "${PY}" >>"${GITHUB_ENV}"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v2.0.3
