# yamllint disable rule:line-length
---
name: Terraform Plan

on:
  pull_request:
    branches:
      - main

concurrency: ci-${{ github.repository }}-terraform

permissions: read-all

jobs:
  terraform-plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_DISABLE: 1
      TF_IN_AUTOMATION: 1

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Check out the repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Initialise Terraform
        run: |
          terraform init -input=false -lock-timeout=60s
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Create the plan
        run: |
          terraform plan -compact-warnings -input=false -lock-timeout=60s -out=terraform.tfplan
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_aws_allowed_account_id: ${{ secrets.AWS_ALLOWED_ACCOUNT_ID }}
          TF_VAR_tf_github_token: ${{ secrets.TF_GITHUB_TOKEN }}

      - id: show
        name: Read the plan
        run: |
          terraform show -no-color terraform.tfplan

      - name: Comment on the PR
        uses: unsplash/comment-on-pr@ffe8f97ccc63ce12c3c23c6885b169db67958d3b # v1.3.0
        with:
          msg: |
            ```hcl
            ${{ steps.show.outputs.stdout }}
            ```
          check_for_duplicate_msg: false
          delete_prev_regex_msg: Terraform will perform the following actions:|Changes to Outputs:|Your infrastructure matches the configuration\.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
