# yamllint disable rule:line-length
---
name: Terraform Plan

on:
  pull_request:
    branches:
      - main

concurrency: ci-${{ github.repository }}-terraform

jobs:
  terraform-plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_DISABLE: 1
      TF_IN_AUTOMATION: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Initialise Terraform
        run: |
          terraform init -input=false -lock-timeout=60s
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Create the plan
        run: |
          terraform plan -compact-warnings -input=false -lock-timeout=60s -out=terraform.tfplan
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_aws_allowed_account_id: ${{ secrets.AWS_ALLOWED_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_tf_github_token: ${{ secrets.TF_GITHUB_TOKEN }}

      - id: show
        name: Read the plan
        run: |
          terraform show -no-color terraform.tfplan

      - name: Comment on the PR
        uses: unsplash/comment-on-pr@v1.3.0
        with:
          msg: |
            ```hcl
            ${{ steps.show.outputs.stdout }}
            ```
          check_for_duplicate_msg: false
          delete_prev_regex_msg: Terraform will perform the following actions:|Changes to Outputs:|Your infrastructure matches the configuration\.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
