# yamllint disable rule:line-length
---
name: Terraform Plan

on:
  pull_request:
    branches:
      - main

concurrency: ci-${{ github.repository }}-terraform

permissions: read-all

jobs:
  terraform-plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_DISABLE: 1
      TF_IN_AUTOMATION: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Initialise Terraform
        run: |
          terraform init -input=false -lock-timeout=60s
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Create the plan
        run: |
          terraform plan -compact-warnings -input=false -lock-timeout=60s -out=terraform.tfplan
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_aws_allowed_account_id: ${{ secrets.AWS_ALLOWED_ACCOUNT_ID }}
          TF_VAR_tf_github_token: ${{ secrets.TF_GITHUB_TOKEN }}

      - id: show
        name: Read the plan
        run: |
          terraform show -no-color terraform.tfplan

      - name: Comment on the PR
        uses: unsplash/comment-on-pr@ffe8f97ccc63ce12c3c23c6885b169db67958d3b # v1.3.0
        with:
          msg: |
            ```hcl
            ${{ steps.show.outputs.stdout }}
            ```
          check_for_duplicate_msg: false
          delete_prev_regex_msg: Terraform will perform the following actions:|Changes to Outputs:|Your infrastructure matches the configuration\.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
