---
name: tfsec

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: 44 2 * * 6

jobs:
  tfsec:
    name: Run tfsec SARIF report
    permissions:
      actions: read
      contents: read
      security-events: write
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.2.0

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2.1.38
        with:
          sarif_file: tfsec.sarif
