# yamllint disable rule:line-length
---
name: Trivy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: 44 2 * * 6

permissions: read-all

jobs:
  tfsec:
    name: Run Trivy SARIF report
    permissions:
      actions: read
      contents: read
      security-events: write
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Run analysis
        uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # v0.17.0
        with:
          exit-code: 1
          format: sarif
          hide-progress: false
          ignore-unfixed: true
          output: trivy-results.sarif
          scan-type: config
          severity: CRITICAL,HIGH

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@e2e140ad1441662206e8f97754b166877dfa1c73 # v3.24.4
        with:
          sarif_file: trivy-results.sarif
