# yamllint disable rule:line-length
---
name: Trivy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: 44 2 * * 6

permissions: read-all

jobs:
  tfsec:
    name: Run Trivy SARIF report
    permissions:
      actions: read
      contents: read
      security-events: write
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run analysis
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
        with:
          exit-code: 1
          format: sarif
          hide-progress: false
          ignore-unfixed: true
          output: trivy-results.sarif
          scan-type: config
          severity: CRITICAL,HIGH

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@aa578102511db1f4524ed59b8cc2bae4f6e88195 # v3.27.6
        with:
          sarif_file: trivy-results.sarif
